#!/usr/bin/env node
// Generate CATALOG.md (a browsable index of every entry) and splice a live
// stats block into README.md. Both are derived purely from data/ — no network,
// no reparse beyond listEntries/loadCategories.
//
//   node scripts/build-catalog.mjs          # write CATALOG.md + update README block
//   node scripts/build-catalog.mjs --check   # regenerate in memory, diff vs on-disk,
//                                             # exit 1 on drift (verify-all stage; CI)
//
// The output contains NO generation timestamp on purpose: a "generated on
// <today>" line would make the drift-check fail every day. Freshness comes
// from added_date/stars in the data, which only change with real edits.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { listEntries, loadCategories, resolveDataDir } from "../mcp-server/lib/store.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CATALOG_PATH = join(ROOT, "CATALOG.md");
const README_PATH = join(ROOT, "README.md");
const START = "<!-- library-stats:start -->";
const END = "<!-- library-stats:end -->";

// GitHub heading-anchor algorithm: lowercase, strip anything but
// alphanumerics/space/hyphen, spaces -> hyphens.
function anchor(text) {
  return text.toLowerCase().replace(/[^a-z0-9 -]/g, "").replace(/ /g, "-");
}

const STATUS_MARK = { active: "", stale: " ⚠ stale", archived: " ⛔ archived" };

// Repo-relative POSIX link path for an entry's Markdown link. `entryPath` comes
// from a node:path join, so it carries '\' separators on Windows — which break
// GitHub Markdown links AND make the --check drift guard fail locally. We
// normalize backslashes explicitly (NOT via path.sep): path.sep is '/' on CI's
// Linux, so a sep-based split would silently no-op there and let the Windows
// regression slip past both --check (no backslashes on Linux) and any test.
export function catalogLinkPath(entryPath, root, categoryId, entryId) {
  const rel = entryPath.startsWith(root)
    ? entryPath.slice(root.length + 1)
    : `data/entries/${categoryId}/${entryId.split("/").pop()}.md`;
  return rel.replace(/\\/g, "/");
}

export function buildCatalog(entries, categories) {
  const byCat = new Map(categories.map((c) => [c.id, []]));
  for (const e of entries) {
    if (byCat.has(e.meta.category)) byCat.get(e.meta.category).push(e);
  }

  const lines = [];
  lines.push("# LibrAIum Catalog");
  lines.push("");
  lines.push(
    `_${entries.length} repositories across ${categories.length} categories. ` +
      "Auto-generated by `scripts/build-catalog.mjs` — do not edit by hand._"
  );
  lines.push("");
  lines.push("## Contents");
  lines.push("");
  for (const c of categories) {
    const n = byCat.get(c.id)?.length ?? 0;
    lines.push(`- [${c.name}](#${anchor(c.name)}) (${n})`);
  }
  lines.push("");

  for (const c of categories) {
    const inCat = (byCat.get(c.id) ?? []).slice().sort((a, b) => (b.meta.stars ?? 0) - (a.meta.stars ?? 0));
    lines.push(`## ${c.name}`);
    lines.push("");
    if (c.description) {
      lines.push(`_${c.description}_`);
      lines.push("");
    }
    if (!inCat.length) {
      lines.push("_(empty shelf)_");
      lines.push("");
      continue;
    }
    lines.push("| Repo | Stars | Language | Tags |");
    lines.push("| --- | --- | --- | --- |");
    for (const e of inCat) {
      const link = `[${e.meta.full_name}](${catalogLinkPath(e.path, ROOT, c.id, e.id)})`;
      const lang = e.meta.language ?? "—";
      const tags = (e.meta.tags ?? []).join(", ");
      lines.push(`| ${link}${STATUS_MARK[e.meta.status] ?? ""} | ${e.meta.stars ?? 0} | ${lang} | ${tags} |`);
    }
    lines.push("");
  }

  // Tag index: tag -> the repos carrying it, alphabetical.
  const tagMap = new Map();
  for (const e of entries) {
    for (const t of e.meta.tags ?? []) {
      const k = t.toLowerCase();
      if (!tagMap.has(k)) tagMap.set(k, []);
      tagMap.get(k).push(e.meta.full_name);
    }
  }
  lines.push("## Tag index");
  lines.push("");
  for (const tag of [...tagMap.keys()].sort()) {
    const repos = tagMap.get(tag).sort();
    lines.push(`- **${tag}** (${repos.length}): ${repos.join(", ")}`);
  }
  lines.push("");
  return lines.join("\n");
}

export function buildStatsBlock(entries, categories) {
  const langs = {};
  for (const e of entries) {
    if (e.meta.language) langs[e.meta.language] = (langs[e.meta.language] ?? 0) + 1;
  }
  const topLangs = Object.entries(langs)
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, 5)
    .map(([l, n]) => `${l} (${n})`)
    .join(", ");
  const stale = entries.filter((e) => e.meta.status === "stale").length;
  const archived = entries.filter((e) => e.meta.status === "archived").length;
  const recent = entries
    .filter((e) => e.meta.added_date)
    .sort((a, b) => b.meta.added_date.localeCompare(a.meta.added_date) || a.id.localeCompare(b.id))
    .slice(0, 5)
    .map((e) => `[${e.meta.full_name}](CATALOG.md#${anchor(catName(categories, e.meta.category))})`)
    .join(", ");

  return [
    START,
    `**${entries.length} repositories** across **${categories.length} categories** — browse them all in [CATALOG.md](CATALOG.md).`,
    "",
    `- Top languages: ${topLangs || "—"}`,
    `- Freshness: ${stale} stale, ${archived} archived`,
    `- Recently added: ${recent || "—"}`,
    END,
  ].join("\n");
}

function catName(categories, id) {
  return categories.find((c) => c.id === id)?.name ?? id;
}

function spliceReadme(readme, block) {
  const s = readme.indexOf(START);
  const e = readme.indexOf(END);
  if (s === -1 || e === -1) {
    throw new Error(`README.md is missing the ${START} / ${END} markers`);
  }
  return readme.slice(0, s) + block + readme.slice(e + END.length);
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  const dataDir = resolveDataDir();
  const entries = listEntries(dataDir);
  const categories = loadCategories(dataDir);
  const catalog = buildCatalog(entries, categories);
  const block = buildStatsBlock(entries, categories);
  const readmeNow = readFileSync(README_PATH, "utf8");
  const readmeNext = spliceReadme(readmeNow, block);

  if (process.argv.includes("--check")) {
    const drift = [];
    let catalogNow = "";
    try {
      catalogNow = readFileSync(CATALOG_PATH, "utf8");
    } catch {
      /* missing = drift */
    }
    if (catalogNow !== catalog) drift.push("CATALOG.md");
    if (readmeNow !== readmeNext) drift.push("README.md stats block");
    if (drift.length) {
      console.error(`✗ catalog drift in: ${drift.join(", ")} — run: node scripts/build-catalog.mjs`);
      process.exit(1);
    }
    console.log("✓ catalog is in sync with data/");
    process.exit(0);
  }

  writeFileSync(CATALOG_PATH, catalog);
  writeFileSync(README_PATH, readmeNext);
  console.log(`wrote CATALOG.md (${entries.length} entries) and refreshed the README stats block`);
}
